/**
 * The library, in code — the destinations that exist, authored by hand.
 *
 * A destination is a LOOK and a VOICE (src/lib/tokens.ts) and the two are one
 * object, because one object is what both consumers read: the renderer takes
 * the look, the writer takes the voice, and neither can be given a destination
 * that is only half specified.
 *
 * ── Why these live in a module and not only in the database ──────────
 *
 * They will live in the database — `world.tokens` for the look and a versioned
 * `world_voice` row for the voice (db/004-destination-voice.sql). This module
 * is not a cache of that and must never become one. It is the CANONICAL,
 * REVIEWABLE text of a destination: a thing a curator and an engineer can read
 * in a diff, argue about in a pull request, and seed from. The same reasoning
 * as src/lib/quiz.ts — the vocabulary is data, and data that decides how the
 * product sounds deserves review, not an admin form and a prayer.
 *
 * Framework-free, like everything it imports. No React, no "server-only", so a
 * script can print a writer prompt without starting Next.
 *
 * ── The type, for now ────────────────────────────────────────────────
 *
 * Every destination uses the three faces src/app/fonts.css declares, because
 * that file is GENERATED by scripts/build-fonts.py and naming a fourth family
 * here would silently fall through to a system fallback. Giving a destination
 * its own face is a real change with a real cost: add it to build-fonts.py,
 * re-run the build, ship the woff2. Until then a destination differentiates on
 * palette and on voice, which is where the difference is felt anyway.
 */

import type { Destination, Theme } from "./tokens";
import type { ToneWeight } from "./voice";

/**
 * WESTHAMPTON, 1976.
 *
 * The founder's tone target, and the first destination written end to end.
 * docs/copy-brief.md keeps it as the standard: "confident, specific, funny
 * without performing".
 */
const WESTHAMPTON_LOOK: Theme = {
  key: "westhampton-1976",
  type: {
    // Didone on a fashion page is the single most 1976 thing about this
    // destination, and it is already on the shelf.
    display: '"Bodoni Moda", Didot, "Bodoni MT", Georgia, serif',
    body: '"Karla", "Helvetica Neue", Arial, sans-serif',
    mono: '"Space Mono", ui-monospace, Menlo, monospace',
  },
  palette: {
    // Sun-bleached canvas, awning green, brass, and the tomato red of a
    // lipstick left on a glass. Nothing avocado; this is the Atlantic, not a
    // kitchen appliance.
    ground: "#E9DCC4",
    ground2: "#DCCBAC",
    ink: "#26251C",
    inkSoft: "#55523F",
    inkFaint: "#8A8570",
    rule: "#C4B393",
    aqua: "#2C6157",
    oxblood: "#B0432C",
    gold: "#BE8A2C",
    night: "#161E1A",
    night2: "#0F1512",
    nightInk: "#EDE2CC",
    nightSoft: "#ABA28C",
    nightAqua: "#79B3A3",
    nightOxblood: "#DE7B54",
    bone: "#F2EEE2",
  },
  paletteDark: {
    ground: "#0F1512",
    ground2: "#161E1A",
    ink: "#EDE2CC",
    inkSoft: "#ABA28C",
    inkFaint: "#7B7461",
    rule: "#2C3A33",
    aqua: "#79B3A3",
    oxblood: "#DE7B54",
    gold: "#D7A64C",
  },
};

export const WESTHAMPTON_1976: Destination = {
  key: "westhampton-1976",
  name: "WESTHAMPTON, 1976",
  tagline: "Vintage summer glamour. Very questionable houseguests.",
  premise:
    "Dune Road, Labor Day weekend, 1976. A rented house that sleeps six, a " +
    "heat wave that does not break, and a long dinner that turns into " +
    "something else.",
  look: WESTHAMPTON_LOOK,
  voiceVersion: 1,
  voice: {
    speaker: "The house.",
    selfReference: ["the house", "the house on Dune Road"],
    audience: "houseguests — people who are already coming",
    address: {
      mode: "impersonal",
      note:
        "Arrangements are stated impersonally: breakfast, the hour, the " +
        "record player. Second person is spent only on arrival and departure " +
        "— you are expected, you are welcome to stay — and never on " +
        "enthusiasm.",
    },

    register:
      "A card left on the hall table by someone who has already gone to bed.",
    formality: "cordial",
    cadence:
      "Short declaratives. A noun phrase is a whole sentence. Two beats and " +
      "stop; the third beat is where a line starts performing.",
    sentence: { typicalWords: 8, maxWords: 16 },
    punctuation:
      "Periods, and a comma where the breath is. A colon only when a list is " +
      "genuinely coming. No exclamation points. No ellipses, no parentheses, " +
      "no dash held open for effect, and no quotation marks around a word " +
      "that is being nudged.",
    orthography:
      "Hours in words: seven o'clock, half past one, after midnight. Days by " +
      "name: Friday, Labor Day weekend. Headings in full caps; nothing else " +
      "is capitalised for emphasis. Contractions are fine in a note left for " +
      "one person and avoided in anything printed and posted.",

    humour: {
      mode: "dry",
      mechanism:
        "State a plain arrangement, then add one true detail that gives away " +
        "what kind of weekend this is — and do not go back for it. The joke " +
        "is always a fact. Never a pun, never a wink, never a second sentence " +
        "explaining the first.",
    },

    lexicon: [
      {
        term: "the house",
        gloss: "the place and everyone in it, spoken of as one thing",
        insteadOf: ["the venue", "the property", "the rental"],
      },
      {
        term: "houseguests",
        gloss: "the people staying. Anyone who merely came to dinner is not one",
        insteadOf: ["attendees", "the group", "everybody"],
      },
      {
        term: "the weekend",
        gloss: "the whole occasion, start to finish",
        insteadOf: ["the event", "the celebration", "the party", "festivities"],
      },
      {
        term: "drinks",
        gloss: "the hour before dinner, and the thing in your hand during it",
        insteadOf: ["cocktail hour", "happy hour", "beverages"],
      },
      {
        term: "the record player",
        gloss: "the stereo, and the standing dispute about it",
        insteadOf: ["the playlist", "the speakers", "the music"],
      },
      {
        term: "the porch",
        gloss: "where the night goes after the table",
        insteadOf: ["the patio", "the outdoor space"],
      },
      {
        term: "Dune Road",
        gloss: "the address. Used in place of directions, which are not given",
        insteadOf: ["the location", "the address below"],
      },
      {
        term: "regrets only",
        gloss: "the reply convention. Silence is a yes",
        insteadOf: ["RSVP", "please confirm", "let us know"],
      },
      {
        term: "the ice",
        gloss:
          "the standing problem of the weekend, referred to as though it were weather",
      },
    ],

    formulae: [
      "{Arrangement} at {hour}. {The second arrangement} when it suits us.",
      "The house is open from {day}.",
      "{Plain fact about the house}, and has {the worse version of the same fact}.",
      "{Flat statement}. It has never mattered.",
      "There is one rule and it concerns {the thing}.",
      "{Meal or ritual} is {one understated adjective}.",
      "Regrets only, and not to {someone who will not pass them on}.",
    ],

    banned: [
      "event",
      "celebration",
      "festivities",
      "soirée",
      "curated",
      "elevated",
      "experience",
      "vibe",
      "iconic",
      "unforgettable",
      "magical",
      "memories",
      "amazing",
      "guys",
      "hosted by",
      "join us",
    ],

    signOffs: [
      "The house, Dune Road.",
      "Regrets only.",
      "The house does not wait dinner.",
      "Come Friday.",
    ],

    always: [
      "Name a real thing: a road, an hour, a drink, a record, a room.",
      "Let the hour do the work. Seven o'clock and after midnight are two different weekends.",
      "Put the arrangement first. If there is a joke it is the last four words.",
      "Assume the reader is already coming.",
    ],

    never: [
      "Never an exclamation point.",
      "Never name the feeling — no glamour, no magic, no unforgettable, no memories.",
      "Never explain a joke, and never explain the house.",
      "Never mention anything that did not exist in 1976. No links, no apps, no playlists, no confirming online.",
      "Never perform the period. No darling, no swell, no groovy — the house is not doing an impression of itself.",
      "Never wink at the reader about what goes on here. State it plainly or leave it out.",
      "Never instruct, apologise, or thank. The house does not thank people for coming to it.",
      "Never address the room by a nickname. No ladies, no everyone, no team.",
      "Never use italics.",
    ],

    breaksCharacterFor: [
      "Anything a guest has to act on to arrive or to be safe: an address, a locked door, a hospital, an allergy. Fact first, fewest words, no joke.",
      "Anything about money.",
      "Any message that gives someone a way out — a decline, a cancellation, a way off a list. Written straight and made easy.",
    ],

    exemplars: [
      {
        piece: "invitation",
        text: "Dune Road, Friday. Drinks at seven, dinner when it suits us.",
      },
      {
        piece: "invitation",
        text: "The house sleeps six and has slept nine. Labor Day weekend.",
        note: "The whole voice in twelve words: an arrangement, then the fact that gives it away.",
      },
      {
        piece: "invitation",
        text: "You are expected Friday. Regrets only, and not to me.",
      },
      {
        piece: "invitation",
        text: "Bring a swimsuit and something for the second night.",
      },
      { piece: "menu_item", text: "Oysters, until they are gone." },
      {
        piece: "menu_item",
        text: "Cold roast chicken. Dinner, or three in the morning.",
      },
      {
        piece: "menu_item",
        text: "Vodka, grapefruit, salt. Called something else after midnight.",
      },
      {
        piece: "menu_item",
        text: "White burgundy, poured generously and not discussed.",
      },
      {
        piece: "notice",
        text: "There is one rule and it concerns the record player.",
      },
      { piece: "notice", text: "Breakfast is theoretical." },
      {
        piece: "notice",
        text: "The upstairs bathroom door does not lock. It has never mattered.",
      },
      {
        piece: "notice",
        text: "Cars face the road. Someone always leaves early.",
      },
      {
        piece: "house_note",
        text: "Your room is the one at the end. The window sticks; push from the left.",
      },
      {
        piece: "house_note",
        text: "Towels are in the hall. The good ones go to the beach, which is a decision the house stands by.",
      },
      { piece: "place_card", text: "Nora — away from the record player." },
      { piece: "place_card", text: "Charles — beside someone he has not met." },
      { piece: "heading", text: "DRINKS, AND WHAT FOLLOWS" },
      { piece: "heading", text: "SUNDAY, SUCH AS IT IS" },
      {
        piece: "bulletin",
        text: "Saturday. The heat holds. Someone has moved the umbrella and will not say who.",
      },
      {
        piece: "game_rule",
        text: "Everyone names a houseguest. Nobody names themselves. The house keeps score and will not show it.",
      },
      { piece: "sign_off", text: "The house, Dune Road." },
      { piece: "sign_off", text: "The house does not wait dinner." },
    ],

    rejected: [
      {
        text: "Vintage summer glamour awaits.",
        why: "Names the feeling. The tagline may say it once, on the cover; nothing inside the destination may say it at all.",
      },
      {
        text: "A weekend of sun, sea and very bad behaviour.",
        why: "The three-item list with the joke in the third slot — the shape every generated line reaches for. It also announces the behaviour instead of arranging it.",
      },
      {
        text: "What happens on Dune Road stays on Dune Road.",
        why: "A borrowed joke and a wink. The house states the hour and lets the reader work out the rest.",
      },
      {
        text: "The record player is not a democracy.",
        why: "A joke about the rule. The rule is funnier stated as a rule.",
      },
      {
        text: "Dinner at eight, darlings.",
        why: "Performing the period. The voice is 1976, not an impression of 1976.",
      },
      {
        text: "The house sleeps six, wink wink.",
        why: "Explains its own joke. The line was already finished four words earlier.",
      },
      {
        text: "Please RSVP by Friday so we can plan accordingly.",
        why: "Administrative. The house does not plan accordingly and does not ask twice.",
      },
    ],
  },
};

/**
 * WESTHAMPTON's voice, said in the tones a host is shown.
 *
 * ── WHY THE CATALOGUE IS TAGGED IN THE HOST'S VOCABULARY ─────────────
 *
 * The tones in src/lib/voice.ts are the whole width of the channel between a
 * host and this library. Describing a destination in anything richer — its own
 * private axes, tuned by hand — would leave the join between her handful of
 * taps and that description returning mush, because she was never given a way
 * to make most of those claims. So both sides are said in the same fifty words,
 * and the vocabulary is falsifiable: if a destination's voice cannot be written
 * in six to ten of them, the tones are wrong and get fixed.
 *
 * Every tag below points at a line in the voice above, not at an impression:
 *
 *   deadpan          "The house sleeps six and has slept nine."
 *   dry_aside        "Put the arrangement first. If there is a joke it is the
 *                     last four words."
 *   understated      "Two beats and stop; the third beat is where a line
 *                     starts performing."
 *   explains_nothing "Never explain a joke, and never explain the house."
 *   never_performs   "Never perform the period." "Never wink at the reader."
 *   low_voices       "A card left on the hall table by someone who has already
 *                     gone to bed."
 *   unhurried        "Drinks at seven, dinner when it suits us."
 *   exact_word       Hours in words, days by name, notices and not
 *                     announcements.
 *   nothing_sacred   "The upstairs bathroom door does not lock. It has never
 *                     mattered." Faint on purpose: the house is disreputable
 *                     about what happens in it and never crude in how it says
 *                     so, which is the difference between 0.35 and 1.
 *
 * Formality, address and humour mode are NOT tagged here. The voice above
 * states them outright — cordial, impersonal, dry — and they are derived from
 * it by `statedVoiceFacets`. Saying a fact twice is how two copies of it start
 * to disagree.
 */
export const WESTHAMPTON_1976_TONES: readonly ToneWeight[] = [
  { code: "deadpan", weight: 1 },
  { code: "understated", weight: 1 },
  { code: "explains_nothing", weight: 0.9 },
  { code: "never_performs", weight: 0.9 },
  { code: "dry_aside", weight: 0.8 },
  { code: "low_voices", weight: 0.7 },
  { code: "unhurried", weight: 0.6 },
  { code: "exact_word", weight: 0.5 },
  { code: "nothing_sacred", weight: 0.35 },
];

/**
 * Every destination that exists, by slug — the same slug as `world.slug`.
 *
 * A plain object rather than a Map so it survives being imported by a script,
 * a route handler, and a seed, and so a missing key is a compile error rather
 * than a runtime undefined.
 */
export const DESTINATIONS = {
  "westhampton-1976": WESTHAMPTON_1976,
} as const satisfies Record<string, Destination>;

export type DestinationKey = keyof typeof DESTINATIONS;

/**
 * How every destination sounds, by the same slug.
 *
 * `satisfies Record<DestinationKey, …>` is the point: a destination cannot be
 * added without saying how it sounds in the vocabulary a host answers in, which
 * is the mistake this file would otherwise make six destinations from now. The
 * seed script writes these into world_facet, where a curator may then revise
 * them without touching this module.
 */
export const DESTINATION_TONES = {
  "westhampton-1976": WESTHAMPTON_1976_TONES,
} as const satisfies Record<DestinationKey, readonly ToneWeight[]>;
