/**
 * The library, in code — the destinations that exist, authored by hand.
 *
 * A destination is a LOOK and a VOICE (src/lib/tokens.ts) and the two are one
 * object, because one object is what both consumers read: the renderer takes
 * the look, the writer takes the voice, and neither can be given a destination
 * that is only half specified.
 *
 * ── Why these live in a module and not only in the database ──────────
 *
 * They will live in the database — `world.tokens` for the look and a versioned
 * `world_voice` row for the voice (db/004-destination-voice.sql). This module
 * is not a cache of that and must never become one. It is the CANONICAL,
 * REVIEWABLE text of a destination: a thing a curator and an engineer can read
 * in a diff, argue about in a pull request, and seed from. The same reasoning
 * as src/lib/quiz.ts — the vocabulary is data, and data that decides how the
 * product sounds deserves review, not an admin form and a prayer.
 *
 * Framework-free, like everything it imports. No React, no "server-only", so a
 * script can print a writer prompt without starting Next.
 *
 * ── The type, for now ────────────────────────────────────────────────
 *
 * Every destination uses the three faces src/app/fonts.css declares, because
 * that file is GENERATED by scripts/build-fonts.py and naming a fourth family
 * here would silently fall through to a system fallback. Giving a destination
 * its own face is a real change with a real cost: add it to build-fonts.py,
 * re-run the build, ship the woff2. Until then a destination differentiates on
 * palette and on voice, which is where the difference is felt anyway.
 */

import type { Destination, Theme } from "./tokens";
import type { ToneWeight } from "./voice";

/**
 * WESTHAMPTON, 1976.
 *
 * The founder's tone target, and the first destination written end to end.
 * docs/copy-brief.md keeps it as the standard: "confident, specific, funny
 * without performing".
 */
const WESTHAMPTON_LOOK: Theme = {
  key: "westhampton-1976",
  type: {
    // Didone on a fashion page is the single most 1976 thing about this
    // destination, and it is already on the shelf.
    display: '"Bodoni Moda", Didot, "Bodoni MT", Georgia, serif',
    body: '"Karla", "Helvetica Neue", Arial, sans-serif',
    mono: '"Space Mono", ui-monospace, Menlo, monospace',
  },
  palette: {
    // Sun-bleached canvas, awning green, brass, and the tomato red of a
    // lipstick left on a glass. Nothing avocado; this is the Atlantic, not a
    // kitchen appliance.
    ground: "#E9DCC4",
    ground2: "#DCCBAC",
    ink: "#26251C",
    inkSoft: "#55523F",
    inkFaint: "#8A8570",
    rule: "#C4B393",
    aqua: "#2C6157",
    oxblood: "#B0432C",
    gold: "#BE8A2C",
    night: "#161E1A",
    night2: "#0F1512",
    nightInk: "#EDE2CC",
    nightSoft: "#ABA28C",
    nightAqua: "#79B3A3",
    nightOxblood: "#DE7B54",
    bone: "#F2EEE2",
  },
  paletteDark: {
    ground: "#0F1512",
    ground2: "#161E1A",
    ink: "#EDE2CC",
    inkSoft: "#ABA28C",
    inkFaint: "#7B7461",
    rule: "#2C3A33",
    aqua: "#79B3A3",
    oxblood: "#DE7B54",
    gold: "#D7A64C",
  },
};

export const WESTHAMPTON_1976: Destination = {
  key: "westhampton-1976",
  name: "WESTHAMPTON, 1976",
  tagline: "Vintage summer glamour. Very questionable houseguests.",
  premise:
    "Dune Road, Labor Day weekend, 1976. A rented house that sleeps six, a " +
    "heat wave that does not break, and a long dinner that turns into " +
    "something else.",
  look: WESTHAMPTON_LOOK,
  voiceVersion: 1,
  voice: {
    speaker: "The house.",
    selfReference: ["the house", "the house on Dune Road"],
    audience: "houseguests — people who are already coming",
    address: {
      mode: "impersonal",
      note:
        "Arrangements are stated impersonally: breakfast, the hour, the " +
        "record player. Second person is spent only on arrival and departure " +
        "— you are expected, you are welcome to stay — and never on " +
        "enthusiasm.",
    },

    register:
      "A card left on the hall table by someone who has already gone to bed.",
    formality: "cordial",
    cadence:
      "Short declaratives. A noun phrase is a whole sentence. Two beats and " +
      "stop; the third beat is where a line starts performing.",
    sentence: { typicalWords: 8, maxWords: 16 },
    punctuation:
      "Periods, and a comma where the breath is. A colon only when a list is " +
      "genuinely coming. No exclamation points. No ellipses, no parentheses, " +
      "no dash held open for effect, and no quotation marks around a word " +
      "that is being nudged.",
    orthography:
      "Hours in words: seven o'clock, half past one, after midnight. Days by " +
      "name: Friday, Labor Day weekend. Headings in full caps; nothing else " +
      "is capitalised for emphasis. Contractions are fine in a note left for " +
      "one person and avoided in anything printed and posted.",

    humour: {
      mode: "dry",
      mechanism:
        "State a plain arrangement, then add one true detail that gives away " +
        "what kind of weekend this is — and do not go back for it. The joke " +
        "is always a fact. Never a pun, never a wink, never a second sentence " +
        "explaining the first.",
    },

    lexicon: [
      {
        term: "the house",
        gloss: "the place and everyone in it, spoken of as one thing",
        insteadOf: ["the venue", "the property", "the rental"],
      },
      {
        term: "houseguests",
        gloss: "the people staying. Anyone who merely came to dinner is not one",
        insteadOf: ["attendees", "the group", "everybody"],
      },
      {
        term: "the weekend",
        gloss: "the whole occasion, start to finish",
        insteadOf: ["the event", "the celebration", "the party", "festivities"],
      },
      {
        term: "drinks",
        gloss: "the hour before dinner, and the thing in your hand during it",
        insteadOf: ["cocktail hour", "happy hour", "beverages"],
      },
      {
        term: "the record player",
        gloss: "the stereo, and the standing dispute about it",
        insteadOf: ["the playlist", "the speakers", "the music"],
      },
      {
        term: "the porch",
        gloss: "where the night goes after the table",
        insteadOf: ["the patio", "the outdoor space"],
      },
      {
        term: "Dune Road",
        gloss: "the address. Used in place of directions, which are not given",
        insteadOf: ["the location", "the address below"],
      },
      {
        term: "regrets only",
        gloss: "the reply convention. Silence is a yes",
        insteadOf: ["RSVP", "please confirm", "let us know"],
      },
      {
        term: "the ice",
        gloss:
          "the standing problem of the weekend, referred to as though it were weather",
      },
    ],

    formulae: [
      "{Arrangement} at {hour}. {The second arrangement} when it suits us.",
      "The house is open from {day}.",
      "{Plain fact about the house}, and has {the worse version of the same fact}.",
      "{Flat statement}. It has never mattered.",
      "There is one rule and it concerns {the thing}.",
      "{Meal or ritual} is {one understated adjective}.",
      "Regrets only, and not to {someone who will not pass them on}.",
    ],

    banned: [
      "event",
      "celebration",
      "festivities",
      "soirée",
      "curated",
      "elevated",
      "experience",
      "vibe",
      "iconic",
      "unforgettable",
      "magical",
      "memories",
      "amazing",
      "guys",
      "hosted by",
      "join us",
    ],

    signOffs: [
      "The house, Dune Road.",
      "Regrets only.",
      "The house does not wait dinner.",
      "Come Friday.",
    ],

    always: [
      "Name a real thing: a road, an hour, a drink, a record, a room.",
      "Let the hour do the work. Seven o'clock and after midnight are two different weekends.",
      "Put the arrangement first. If there is a joke it is the last four words.",
      "Assume the reader is already coming.",
    ],

    never: [
      "Never an exclamation point.",
      "Never name the feeling — no glamour, no magic, no unforgettable, no memories.",
      "Never explain a joke, and never explain the house.",
      "Never mention anything that did not exist in 1976. No links, no apps, no playlists, no confirming online.",
      "Never perform the period. No darling, no swell, no groovy — the house is not doing an impression of itself.",
      "Never wink at the reader about what goes on here. State it plainly or leave it out.",
      "Never instruct, apologise, or thank. The house does not thank people for coming to it.",
      "Never address the room by a nickname. No ladies, no everyone, no team.",
      "Never use italics.",
    ],

    breaksCharacterFor: [
      "Anything a guest has to act on to arrive or to be safe: an address, a locked door, a hospital, an allergy. Fact first, fewest words, no joke.",
      "Anything about money.",
      "Any message that gives someone a way out — a decline, a cancellation, a way off a list. Written straight and made easy.",
    ],

    exemplars: [
      {
        piece: "invitation",
        text: "Dune Road, Friday. Drinks at seven, dinner when it suits us.",
      },
      {
        piece: "invitation",
        text: "The house sleeps six and has slept nine. Labor Day weekend.",
        note: "The whole voice in twelve words: an arrangement, then the fact that gives it away.",
      },
      {
        piece: "invitation",
        text: "You are expected Friday. Regrets only, and not to me.",
      },
      {
        piece: "invitation",
        text: "Bring a swimsuit and something for the second night.",
      },
      { piece: "menu_item", text: "Oysters, until they are gone." },
      {
        piece: "menu_item",
        text: "Cold roast chicken. Dinner, or three in the morning.",
      },
      {
        piece: "menu_item",
        text: "Vodka, grapefruit, salt. Called something else after midnight.",
      },
      {
        piece: "menu_item",
        text: "White burgundy, poured generously and not discussed.",
      },
      {
        piece: "notice",
        text: "There is one rule and it concerns the record player.",
      },
      { piece: "notice", text: "Breakfast is theoretical." },
      {
        piece: "notice",
        text: "The upstairs bathroom door does not lock. It has never mattered.",
      },
      {
        piece: "notice",
        text: "Cars face the road. Someone always leaves early.",
      },
      {
        piece: "house_note",
        text: "Your room is the one at the end. The window sticks; push from the left.",
      },
      {
        piece: "house_note",
        text: "Towels are in the hall. The good ones go to the beach, which is a decision the house stands by.",
      },
      { piece: "place_card", text: "Nora — away from the record player." },
      { piece: "place_card", text: "Charles — beside someone he has not met." },
      { piece: "heading", text: "DRINKS, AND WHAT FOLLOWS" },
      { piece: "heading", text: "SUNDAY, SUCH AS IT IS" },
      {
        piece: "bulletin",
        text: "Saturday. The heat holds. Someone has moved the umbrella and will not say who.",
      },
      {
        piece: "game_rule",
        text: "Everyone names a houseguest. Nobody names themselves. The house keeps score and will not show it.",
      },
      { piece: "sign_off", text: "The house, Dune Road." },
      { piece: "sign_off", text: "The house does not wait dinner." },
    ],

    rejected: [
      {
        text: "Vintage summer glamour awaits.",
        why: "Names the feeling. The tagline may say it once, on the cover; nothing inside the destination may say it at all.",
      },
      {
        text: "A weekend of sun, sea and very bad behaviour.",
        why: "The three-item list with the joke in the third slot — the shape every generated line reaches for. It also announces the behaviour instead of arranging it.",
      },
      {
        text: "What happens on Dune Road stays on Dune Road.",
        why: "A borrowed joke and a wink. The house states the hour and lets the reader work out the rest.",
      },
      {
        text: "The record player is not a democracy.",
        why: "A joke about the rule. The rule is funnier stated as a rule.",
      },
      {
        text: "Dinner at eight, darlings.",
        why: "Performing the period. The voice is 1976, not an impression of 1976.",
      },
      {
        text: "The house sleeps six, wink wink.",
        why: "Explains its own joke. The line was already finished four words earlier.",
      },
      {
        text: "Please RSVP by Friday so we can plan accordingly.",
        why: "Administrative. The house does not plan accordingly and does not ask twice.",
      },
    ],
  },
};

/**
 * WESTHAMPTON's voice, said in the tones a host is shown.
 *
 * ── WHY THE CATALOGUE IS TAGGED IN THE HOST'S VOCABULARY ─────────────
 *
 * The tones in src/lib/voice.ts are the whole width of the channel between a
 * host and this library. Describing a destination in anything richer — its own
 * private axes, tuned by hand — would leave the join between her handful of
 * taps and that description returning mush, because she was never given a way
 * to make most of those claims. So both sides are said in the same fifty words,
 * and the vocabulary is falsifiable: if a destination's voice cannot be written
 * in six to ten of them, the tones are wrong and get fixed.
 *
 * Every tag below points at a line in the voice above, not at an impression:
 *
 *   deadpan          "The house sleeps six and has slept nine."
 *   dry_aside        "Put the arrangement first. If there is a joke it is the
 *                     last four words."
 *   understated      "Two beats and stop; the third beat is where a line
 *                     starts performing."
 *   explains_nothing "Never explain a joke, and never explain the house."
 *   never_performs   "Never perform the period." "Never wink at the reader."
 *   low_voices       "A card left on the hall table by someone who has already
 *                     gone to bed."
 *   unhurried        "Drinks at seven, dinner when it suits us."
 *   exact_word       Hours in words, days by name, notices and not
 *                     announcements.
 *   nothing_sacred   "The upstairs bathroom door does not lock. It has never
 *                     mattered." Faint on purpose: the house is disreputable
 *                     about what happens in it and never crude in how it says
 *                     so, which is the difference between 0.35 and 1.
 *
 * Formality, address and humour mode are NOT tagged here. The voice above
 * states them outright — cordial, impersonal, dry — and they are derived from
 * it by `statedVoiceFacets`. Saying a fact twice is how two copies of it start
 * to disagree.
 */
export const WESTHAMPTON_1976_TONES: readonly ToneWeight[] = [
  { code: "deadpan", weight: 1 },
  { code: "understated", weight: 1 },
  { code: "explains_nothing", weight: 0.9 },
  { code: "never_performs", weight: 0.9 },
  { code: "dry_aside", weight: 0.8 },
  { code: "low_voices", weight: 0.7 },
  { code: "unhurried", weight: 0.6 },
  { code: "exact_word", weight: 0.5 },
  { code: "nothing_sacred", weight: 0.35 },
];

/**
 * HAVANA, THE SMALL HOURS.
 *
 * The first destination the CATALOGUE asked for. Its food and its bar were
 * authored before it had a name — menus 28 and 29 in docs/menus.md, drinks 19
 * and 20 in docs/drinks.md — so the look and the voice below are written to
 * those and not the other way round. Read them first; everything here is an
 * answer to something specific in them.
 *
 * ── WHY THERE IS NO YEAR ─────────────────────────────────────────────
 *
 * WESTHAMPTON is a place and a YEAR. Havana is a place and an HOUR, and the
 * difference is the whole design.
 *
 * Give this destination a decade and there is only one decade anybody reaches
 * for: 1950s Havana as an American playground — the casinos, the linen suits,
 * somebody else's country photographed at its least free. That is kitsch, it is
 * in poor taste, and it is the same failure WESTHAMPTON's own rule already
 * forbids: the house is not doing an impression of itself. The founder's
 * catalogue names no year either. It names an evening with two halves — a long
 * dinner party (28, 19) and A LATE SUPPER AFTER DANCING (29, 20) — which is a
 * structural fact almost nothing else in the library has, and it is a fact
 * about the clock rather than the calendar.
 *
 * So the time is a time of night. It dates nothing, it excludes nobody, and it
 * is the honest reading of the source: coffee at every hour including after
 * midnight, a bar that shakes rather than stirs, and a table that gets carried
 * back against the wall in the middle of the evening.
 *
 * ── THE SECOND TRAP, AND THE RULE IT PRODUCED ────────────────────────
 *
 * WESTHAMPTON speaks as THE HOUSE. Havana speaks as a house too — a house in
 * Havana, in its own words — and the way that goes wrong is impersonation: an
 * accent set down on paper, a word spelled the way a foreigner hears it, an
 * exclamation borrowed to prove where we are. Real nouns are the opposite of
 * caricature. A courtyard, a fan, the Malecón, the ice, the last coffee are
 * facts; a performed accent is a costume. The rule is in `never`, in the
 * house's own words, exactly where WESTHAMPTON keeps its ban on anachronism.
 */
const HAVANA_LOOK: Theme = {
  key: "havana",
  type: {
    // The three faces the repo ships. Havana differentiates on palette and on
    // voice, which is where a destination is felt anyway — see the note at the
    // top of this file about what a fourth family actually costs.
    display: '"Bodoni Moda", Didot, "Bodoni MT", Georgia, serif',
    body: '"Karla", "Helvetica Neue", Arial, sans-serif',
    mono: '"Space Mono", ui-monospace, Menlo, monospace',
  },
  palette: {
    // The house palette turned warm and one shade deeper: rose-ochre plaster,
    // the green-blue every shutter on the street is painted, brass under a
    // bulb, and the red of a roof tile. Recognisably the same seven colours the
    // other eleven plates are drawn in — no turquoise, no hot pink, nothing
    // that belongs on a postcard. This is a courtyard at three in the morning.
    ground: "#F2DCC3",
    ground2: "#E8C9A9",
    ink: "#2B1D16",
    inkSoft: "#63503F",
    inkFaint: "#95826F",
    rule: "#D8BC9B",
    aqua: "#1E6B6E",
    oxblood: "#B8452A",
    gold: "#C08A2E",
    night: "#152622",
    night2: "#0E1B18",
    nightInk: "#F2E2CB",
    nightSoft: "#B4A18A",
    nightAqua: "#5FB6AE",
    nightOxblood: "#E4885C",
    bone: "#F6F0E4",
  },
  paletteDark: {
    ground: "#0E1B18",
    ground2: "#152622",
    ink: "#F2E2CB",
    inkSoft: "#B4A18A",
    inkFaint: "#83745F",
    rule: "#2A403A",
    aqua: "#5FB6AE",
    oxblood: "#E4885C",
    gold: "#DDA84E",
  },
};

export const HAVANA: Destination = {
  key: "havana",
  name: "HAVANA, THE SMALL HOURS",
  tagline: "The table is pushed back for the dancing. Supper again at three.",
  premise:
    "A house on Tejadillo with a courtyard, a fan that turns and does not " +
    "cool, and a night with two halves. Dinner runs until the table is " +
    "carried back against the wall. What follows the dancing is a second " +
    "supper nobody planned and everybody expects.",
  look: HAVANA_LOOK,
  voiceVersion: 1,
  voice: {
    speaker: "The house on Tejadillo, and whoever in it is still up.",
    selfReference: ["we", "the house", "the house on Tejadillo"],
    audience:
      "the people coming to dinner, most of whom will still be here at three",
    address: {
      mode: "collective_first",
      note:
        "Arrangements are said as we: we eat at ten, we move the table, we " +
        "will be up. The we is the household, never a management. Second " +
        "person is spent on the two things a guest acts on — when to come, " +
        "and which room is theirs — and never on enthusiasm.",
    },

    register:
      "A note written standing up in the kitchen at the hour it describes, " +
      "with the coffee going and the music still on in the next room.",
    formality: "plain",
    cadence:
      "A statement, then the thing that actually happens, joined by a comma " +
      "or left as its own sentence. The line ends on an hour or on a plain " +
      "noun. It does not end on a flourish.",
    sentence: { typicalWords: 11, maxWords: 20 },
    punctuation:
      "Periods and commas, and the comma is where the night turns. A colon " +
      "only when a real list is coming. No exclamation points, no ellipses, " +
      "no parentheses, no dash held open for effect, no quotation marks " +
      "around a word that is being nudged, and no semicolons. This is a note, " +
      "not a paragraph.",
    orthography:
      "Hours in words: nine o'clock, half past two, three in the morning, " +
      "first light. Days by name. Headings in full caps, and nothing else is " +
      "capitalised for emphasis. Food and drink get their plain names — a " +
      "plantain is a plantain. A place keeps its own name and its own " +
      "spelling, Tejadillo and the Malecón, and nothing else on the page is " +
      "spelled to sound like anywhere.",

    humour: {
      mode: "warm",
      mechanism:
        "Say the excessive thing as though it were the schedule, and let the " +
        "hour carry it: the second supper, the third coffee, the fan that has " +
        "never worked. Nobody in the house is the target — the night is. " +
        "Never a punchline, never a second sentence explaining the first.",
    },

    lexicon: [
      {
        term: "the house on Tejadillo",
        gloss: "the address. Given in place of directions, which are not given",
        insteadOf: ["the venue", "the location", "the address below"],
      },
      {
        term: "the courtyard",
        gloss: "where the night is, at every hour, whatever the room was for",
        insteadOf: ["the patio", "the terrace", "the outdoor space"],
      },
      {
        term: "the table",
        gloss:
          "the long dinner, and the piece of furniture that gets carried back against the wall",
        insteadOf: ["the dinner party", "the seating", "the spread"],
      },
      {
        term: "the dancing",
        gloss: "the middle of the night, and the reason the table is moved",
        insteadOf: ["the party", "the entertainment", "the dance floor"],
      },
      {
        term: "the second supper",
        gloss:
          "what is eaten after the dancing. Not a snack and not a novelty — the other half of dinner",
        insteadOf: ["late-night bites", "the after-party", "midnight snacks"],
      },
      {
        term: "the coffee",
        gloss: "small, strong, sweet, at any hour. There is never a last one",
        insteadOf: ["espresso", "a nightcap", "caffeine"],
      },
      {
        term: "the fan",
        gloss:
          "the one in the courtyard. It turns and does not cool, and has been like that for years",
        insteadOf: ["the air conditioning", "the breeze"],
      },
      {
        term: "the door is open",
        gloss: "the reply convention. Nobody replies and nobody is counted",
        insteadOf: ["RSVP", "please confirm", "let us know", "regrets only"],
      },
      {
        term: "first light",
        gloss: "when it ends, which is not a decision anyone makes",
        insteadOf: ["the end of the night", "closing time", "last call"],
      },
    ],

    formulae: [
      "{Arrangement} at {hour}. {What actually happens} at {the later hour}.",
      "The door is open from {hour}.",
      "There is coffee {when}.",
      "The table is moved after {the dish}.",
      "{Plain fact about the house}. It has always been like that.",
      "We {do the thing}. Nobody is asked and nobody is counted.",
      "{Dish}, and then {the same thing again, later and smaller}.",
      "Bring nobody who {the thing that ends a night early}.",
    ],

    banned: [
      "sultry",
      "sizzling",
      "steamy",
      "exotic",
      "tropical",
      "paradise",
      "fiesta",
      "salsa",
      "casino",
      "cigar",
      "authentic",
      "escape",
      "curated",
      "elevated",
      "experience",
      "vibe",
      "iconic",
      "unforgettable",
      "magical",
      "memories",
      "guys",
      "hosted by",
      "join us",
    ],

    signOffs: [
      "The house on Tejadillo.",
      "The door is open.",
      "We will be up.",
      "There is coffee.",
    ],

    always: [
      "Name a real thing: a street, an hour, a fan, a glass, a pot of coffee.",
      "Let the hour carry it. Ten o'clock and three in the morning are two different suppers.",
      "Say the arrangement, then say what happens instead of it.",
      "Write as though the music is still on in the next room and one of us is still up.",
      "Assume the reader is coming, and that they will stay too long.",
      "Give the food and the drink their plain names. A plantain is a plantain.",
      "Hand everyone the same glass. What is in it is nobody's business.",
    ],

    never: [
      "Never an exclamation point.",
      "Never name the feeling — no sultry, no magic, no romance, no unforgettable, no memories.",
      "Never put an accent on the page. No phonetic spelling, no borrowed slang, no word set down to sound foreign. A real name is a fact; a spelling that performs an accent is a costume.",
      "Never date the house. No year, no decade, no politics, no casino, no cigar sold as a souvenir. This is somebody's home and it is not a set.",
      "Never borrow another Havana — a song everyone knows, a bar from a paperback, a man who drank somewhere. Nobody here is a stop on a tour.",
      "Never explain the second supper. It is not a novelty and it is not a bit.",
      "Never write the dancing as a performance. Nobody is watching, and the house is not either.",
      "Never write a line that separates the people drinking from the people who are not. Same glass, same lime, no mention.",
      "Never thank people for coming, ask them to reply, or count who is coming.",
      "Never use italics.",
    ],

    breaksCharacterFor: [
      "Anything a guest must act on to arrive or to be safe: the street, the door, the stairs, a hospital, what is in the food. Fact first, fewest words, no joke.",
      "Anything about money.",
      "Any message that lets someone go — a decline, a cancellation, a way off a list. Written straight and made easy.",
    ],

    exemplars: [
      {
        piece: "invitation",
        text: "The house on Tejadillo, Saturday. Come after nine. We eat at ten.",
      },
      {
        piece: "invitation",
        text: "We will feed you twice. The second one is at three.",
        note: "The whole destination in eleven words. The joke is the hour, and the hour is true.",
      },
      {
        piece: "invitation",
        text: "Dinner, and then the table goes back against the wall. Nobody sits down again.",
      },
      { piece: "invitation", text: "The door is open from nine and stays open." },
      { piece: "invitation", text: "Bring nobody who has to be up early." },
      {
        piece: "menu_item",
        text: "Pork with garlic and citrus, in the oven since the afternoon.",
      },
      {
        piece: "menu_item",
        text: "Sweet plantains at the table. The green ones come later, with garlic sauce.",
      },
      {
        piece: "menu_item",
        text: "Black beans and white rice. There is no version of this night without them.",
      },
      {
        piece: "menu_item",
        text: "Daiquiris shaken hard. The same glass, limeade and mint, for whoever would rather.",
      },
      {
        piece: "menu_item",
        text: "Flan, and then coffee. Small cups, strong and sweet, at whatever hour it is.",
      },
      {
        piece: "menu_item",
        text: "Sandwiches pressed flat at half past two, when the dancing lets up.",
      },
      {
        piece: "menu_item",
        text: "Coconut ice cream, eaten standing in the kitchen.",
      },
      {
        piece: "notice",
        text: "There is coffee at every hour, including this one.",
      },
      {
        piece: "notice",
        text: "The table is moved after the flan. Everybody helps and nobody is asked.",
      },
      {
        piece: "notice",
        text: "The fan in the courtyard turns and does not cool. It has always been like that.",
      },
      {
        piece: "notice",
        text: "The stairs to the roof are steep and unlit. Take somebody with you.",
      },
      {
        piece: "house_note",
        text: "Your room is off the courtyard. Leave the window open. The noise stops before it matters.",
      },
      {
        piece: "house_note",
        text: "The coffee pot is never washed with soap. That is not going to change.",
      },
      { piece: "place_card", text: "Marta — where she can see the door." },
      {
        piece: "place_card",
        text: "Rafael — beside somebody who will get him up.",
      },
      {
        piece: "game_rule",
        text: "Everybody names the song that gets them up. Nobody names their own. We play them in order.",
      },
      {
        piece: "bulletin",
        text: "Sunday. The pork went on at two. Somebody has taken the good chair into the courtyard.",
      },
      { piece: "heading", text: "DINNER, AND WHAT THE TABLE IS MOVED FOR" },
      { piece: "heading", text: "AFTER THE DANCING" },
      { piece: "heading", text: "WHAT THERE IS AT THREE" },
      { piece: "sign_off", text: "The house on Tejadillo." },
      { piece: "sign_off", text: "We will be up." },
    ],

    rejected: [
      {
        text: "Havana, 1957. The casino, the linen suits, the last good year.",
        why: "Somebody else's country as a playground, photographed at its least free. Kitsch, and the exact failure the period rule exists to stop.",
      },
      {
        text: "Sultry nights, strong rum, and a rhythm you can feel.",
        why: "Three feelings named in a row and a place sold as a temperature. Brochure.",
      },
      {
        text: "Vamos. Dinner at nine.",
        why: "A word put on the page to sound foreign. The house does not perform its own language.",
      },
      {
        text: "The record on all night, the one everybody knows.",
        why: "Borrows another Havana. A record collection somebody else assembled is not a destination.",
      },
      {
        text: "Cigars on the roof after the second supper.",
        why: "The single most costume object available. Somebody probably did; the page still does not.",
      },
      {
        text: "The dancing starts when the rum runs out.",
        why: "Measures the night in what is in the glass. The mocktail mirror exists so that nobody's evening is counted that way.",
      },
      {
        text: "Come and lose track of time.",
        why: "Names the feeling and instructs. The hours are printed, and the printed hours are the point.",
      },
      {
        text: "A little slice of old Havana.",
        why: "A menu board wrote this. Old Havana is a place, not a mood, and the house is in it.",
      },
    ],
  },
};

/**
 * HAVANA's voice, said in the tones a host is shown.
 *
 * Same discipline as WESTHAMPTON's list above and the same falsifiability test:
 * a destination whose voice cannot be said in six to ten of the fifty is a
 * destination the voice question cannot match, and the answer is to fix the
 * tones rather than to describe around them.
 *
 * Every tag points at a line of the voice above:
 *
 *   good_natured     "Nobody in the house is the target — the night is."
 *                    Carries humour_warm, which is where this house parts
 *                    company with Westhampton's dry.
 *   lingers          "Dinner runs until the table is carried back against the
 *                    wall." A long dinner party is the whole first half.
 *   laughs_first     "the music still on in the next room" — the one tone here
 *                    that puts volume on the positive side, which is the other
 *                    half of the difference from a house where the best line is
 *                    muttered.
 *   says_it_out_loud "We will be up." "We will feed you twice." The fond thing
 *                    said plainly, with no armour on it.
 *   no_speeches      "It does not end on a flourish." "Never write the dancing
 *                    as a performance." The claim AGAINST theatricality, which
 *                    is what keeps a warm house from becoming a loud one.
 *   exact_word       Hours in words, half past two, three in the morning. The
 *                    night is late and the writing about it is exact.
 *   asks_properly    "Take somebody with you." "Leave the window open." The
 *                    house attends to a person without making a thing of it.
 *
 * Formality, address and humour mode are NOT tagged: the voice states them —
 * plain, collective first, warm — and `statedVoiceFacets` derives them. All
 * three differ from Westhampton's, which is the point of authoring a second
 * destination at all. Two houses that resolve to the same vector are one house
 * with two palettes.
 */
export const HAVANA_TONES: readonly ToneWeight[] = [
  { code: "good_natured", weight: 1 },
  { code: "lingers", weight: 0.9 },
  { code: "laughs_first", weight: 0.7 },
  { code: "says_it_out_loud", weight: 0.6 },
  { code: "no_speeches", weight: 0.6 },
  { code: "exact_word", weight: 0.5 },
  { code: "asks_properly", weight: 0.4 },
];

/**
 * Every destination that exists, by slug — the same slug as `world.slug`.
 *
 * A plain object rather than a Map so it survives being imported by a script,
 * a route handler, and a seed, and so a missing key is a compile error rather
 * than a runtime undefined.
 */
export const DESTINATIONS = {
  "westhampton-1976": WESTHAMPTON_1976,
  havana: HAVANA,
} as const satisfies Record<string, Destination>;

export type DestinationKey = keyof typeof DESTINATIONS;

/**
 * How every destination sounds, by the same slug.
 *
 * `satisfies Record<DestinationKey, …>` is the point: a destination cannot be
 * added without saying how it sounds in the vocabulary a host answers in, which
 * is the mistake this file would otherwise make six destinations from now. The
 * seed script writes these into world_facet, where a curator may then revise
 * them without touching this module.
 */
export const DESTINATION_TONES = {
  "westhampton-1976": WESTHAMPTON_1976_TONES,
  havana: HAVANA_TONES,
} as const satisfies Record<DestinationKey, readonly ToneWeight[]>;
