/**
 * GENERATED BY scripts/generate-pool-registry.mjs — DO NOT EDIT BY HAND.
 *
 *     npm run gen:pools
 *
 * WHAT POOLS EXIST. Nothing else. This file is the single answer to a question
 * that used to be answered independently in six places, and got a different
 * answer in four of them (CLAUDE.md rule 19).
 *
 * ── THE BOUNDARY THIS FILE DRAWS ─────────────────────────────────────
 *
 * DERIVED AT RUNTIME, and not here: everything `ingredient_pool` holds that a
 * migration can UPDATE after the fact — `typical_draw`, `label`,
 * `label_column`, `active_column`. db/022 moves dish to 3 and menu to 0
 * without touching any installer call, so a copy here would be a second opinion
 * kept current by hand. src/lib/desk/publish.ts and src/lib/desk/connections.ts
 * read those live and are right to.
 *
 * GENERATED AND VERIFIED, which is this file: WHICH pools exist and what their
 * four scoping tables are called. These are needed as TYPES — `Record<StockedPool,
 * Spec>` in the engine's catalogue, `Taggable` in the desk — and a type is gone
 * before a connection is ever opened, so a runtime read cannot produce the
 * compile error rule 19 asks for. Generating the constant and CHECKING IT
 * AGAINST THE DATABASE IN A TEST is the closest honest thing: the compiler
 * catches the consumer that forgot a pool, and the test catches this file
 * drifting from the schema. Neither alone is enough, which is why it is both.
 *
 * IRREDUCIBLY HAND-AUTHORED, and deliberately absent: which COLUMN holds the
 * sentence a member reads (src/lib/portal/picks.ts's `RENDERING`, and the
 * `describe`/`mirror` fields of the engine's catalogue), and which desk screen
 * shows a pool (src/lib/desk/stocked.ts's `POOL_SCREEN`). A menu's line of
 * dishes IS the thing and a drink carries two authored builds on one row; those
 * are facts about AUTHORING and about ROUTES, the registry has no column for
 * them and should not grow one. What this file gives them is a KEY SET they
 * must cover, so forgetting one is a compile error even though the value
 * itself can only be written by a person.
 */

/** One entity the migrations registered, with the tables they installed. */
export type PoolEntity = {
  /** `ingredient_pool.entity_table` / `facet_tag_entity.entity_table`. */
  readonly pool: string;
  /** It has a row of `ingredient_pool`. False for `taste_cohort` alone. */
  readonly ingredient: boolean;
  /** `ingredient_pool.join_table`. Null for `world` — see below. */
  readonly joinTable: string | null;
  /** `facet_tag_entity.join_table`, always `<pool>_facet`. */
  readonly facetTable: string | null;
  /** `ingredient_pool.occasion_table`. */
  readonly occasionTable: string | null;
  /** `ingredient_pool.slot_table`. */
  readonly slotTable: string | null;
  /** `ingredient_pool.world_table`. */
  readonly worldTable: string | null;
};

/** Every registered entity, both registries, sorted by name. */
export const POOL_ENTITIES = [
  {
    pool: "bank_item",
    ingredient: true,
    joinTable: "revelle_bank_item",
    facetTable: "bank_item_facet",
    occasionTable: "bank_item_occasion",
    slotTable: "bank_item_slot",
    worldTable: "bank_item_world",
  },
  {
    pool: "dish",
    ingredient: true,
    joinTable: "revelle_dish",
    facetTable: "dish_facet",
    occasionTable: "dish_occasion",
    slotTable: "dish_slot",
    worldTable: "dish_world",
  },
  {
    pool: "drink",
    ingredient: true,
    joinTable: "revelle_drink",
    facetTable: "drink_facet",
    occasionTable: "drink_occasion",
    slotTable: "drink_slot",
    worldTable: "drink_world",
  },
  {
    pool: "game",
    ingredient: true,
    joinTable: "revelle_game",
    facetTable: "game_facet",
    occasionTable: "game_occasion",
    slotTable: "game_slot",
    worldTable: "game_world",
  },
  {
    pool: "menu",
    ingredient: true,
    joinTable: "revelle_menu",
    facetTable: "menu_facet",
    occasionTable: "menu_occasion",
    slotTable: "menu_slot",
    worldTable: "menu_world",
  },
  {
    pool: "product",
    ingredient: true,
    joinTable: "revelle_product",
    facetTable: "product_facet",
    occasionTable: "product_occasion",
    slotTable: "product_slot",
    worldTable: "product_world",
  },
  {
    pool: "taste_cohort",
    ingredient: false,
    joinTable: null,
    facetTable: "taste_cohort_facet",
    occasionTable: null,
    slotTable: null,
    worldTable: null,
  },
  {
    pool: "tracklist",
    ingredient: true,
    joinTable: "revelle_tracklist",
    facetTable: "tracklist_facet",
    occasionTable: "tracklist_occasion",
    slotTable: "tracklist_slot",
    worldTable: "tracklist_world",
  },
  {
    pool: "world",
    ingredient: true,
    joinTable: null,
    facetTable: "world_facet",
    occasionTable: "world_occasion",
    slotTable: null,
    worldTable: null,
  },
] as const satisfies readonly PoolEntity[];

/**
 * Anything either registry knows about — including `taste_cohort`, which is
 * tagged but never issued.
 */
export type EntityTable = (typeof POOL_ENTITIES)[number]["pool"];

/**
 * A POOL THE ENGINE CAN DRAW FROM: a row of `ingredient_pool` with a
 * `join_table`.
 *
 * `world` is excluded and that is not an oversight. It has an
 * `ingredient_pool` row with a NULL join table because db/001 already carries
 * the chosen destination as `revelle.world_id`; a destination is the frame the
 * evening is drawn in, not a thing drawn into it. Anything looping to SELECT
 * ingredients wants this union. Anything looping to RENDER a desk screen wants
 * `ENTITY_TABLES`, because destinations have one.
 */
export type StockedPool = Extract<
  (typeof POOL_ENTITIES)[number],
  { ingredient: true; joinTable: string }
>["pool"];

/** An entity with a `<pool>_facet` table, i.e. a row of `facet_tag_entity`. */
export type FacetEntity = Extract<
  (typeof POOL_ENTITIES)[number],
  { facetTable: string }
>["pool"];

/** Every entity name, sorted. */
export const ENTITY_TABLES = [
  "bank_item",
  "dish",
  "drink",
  "game",
  "menu",
  "product",
  "taste_cohort",
  "tracklist",
  "world",
] as const satisfies readonly EntityTable[];

/** The pools the engine can draw from, sorted. Excludes `world`. */
export const STOCKED_POOLS = [
  "bank_item",
  "dish",
  "drink",
  "game",
  "menu",
  "product",
  "tracklist",
] as const satisfies readonly StockedPool[];

/** The entities that can carry facet tags, sorted. */
export const FACET_ENTITIES = [
  "bank_item",
  "dish",
  "drink",
  "game",
  "menu",
  "product",
  "taste_cohort",
  "tracklist",
  "world",
] as const satisfies readonly FacetEntity[];

/**
 * The pools db/033's CHECK on `ingredient_requirement.entity_table` accepts.
 *
 * Read out of the migration rather than assumed equal to `STOCKED_POOLS`,
 * because this constraint HAS DRIFTED: db/020 wrote five pools into it, three
 * more were registered, and db/033 had to repair it. If it ever falls behind
 * again the two lists differ here, in a generated file, and registry.test.ts
 * says so — instead of a curator getting a 500 from a constraint violation.
 */
export const REQUIRABLE_POOLS = [
  "product",
  "game",
  "tracklist",
  "menu",
  "drink",
  "dish",
  "bank_item",
] as const;

export type RequirablePool = (typeof REQUIRABLE_POOLS)[number];

/** Index by pool, for the lookups below. */
const BY_POOL: Readonly<Record<string, PoolEntity>> = Object.fromEntries(
  POOL_ENTITIES.map((entity) => [entity.pool, entity])
);

/**
 * The four scoping tables of one pool, BY LOOKUP RATHER THAN CONCATENATION.
 *
 * The difference matters and is the whole of rule 19's second clause.
 * `${table}_world` at the point of use is a guess that is right until a pool
 * is registered without that installer having run — which is exactly what
 * db/031 did, leaving `bank_item` with a `revelle_bank_item` and no
 * `bank_item_world` until db/043 filled it in. A guess returns a name for a
 * table that does not exist and fails as a 500 at the far end of a query. This
 * returns `null`, in the type, where the caller has to decide what that means.
 */
export function tablesFor(pool: string): PoolEntity | null {
  return BY_POOL[pool] ?? null;
}

/** `<pool>_facet`, from the registry. Never composed at the point of use. */
export function facetTableFor(pool: FacetEntity): string {
  const table = BY_POOL[pool]?.facetTable;
  if (!table) throw new Error(`no facet table registered for pool '${pool}'`);
  return table;
}

/**
 * The column a join table points back at the entity with — `<pool>_id`.
 *
 * Both installers compute it the same way (`v_column := p_entity_table ||
 * '_id'` in db/002 and db/009) and no migration overrides it, so unlike the
 * table names there is nothing per-pool to store. It is derived here, once,
 * next to the migration text it was read from.
 */
export function idColumnFor(pool: EntityTable): string {
  return `${pool}_id`;
}
