import type { ReactNode } from "react";

/**
 * The tone marks — one per tone in src/lib/voice.ts.
 *
 * GENERATED by scripts/build-tone-marks.mjs from design/tone-icons/, which is a
 * design deliverable. DO NOT EDIT THIS FILE: re-cut the SVG and re-run the
 * script, so the drawing and the thing that ships can never disagree.
 *
 * ── WHAT THESE ARE ───────────────────────────────────────────────────
 *
 * Icons of FEELINGS. A host taps the ones that sound like her friends, and
 * those taps are the only signal telling the house what register to write her
 * invitations, menus and place cards in — so she has to be able to feel the
 * difference between deadpan and warm before she reads a word. An earlier set
 * drew conversation instead (a line was a spoken phrase, a dot a person, a gap
 * a silence): internally consistent, and unreadable. It was replaced.
 *
 * ── HOW THEY HOLD TOGETHER ───────────────────────────────────────────
 *
 * Every icon is fitted to the same 46-unit optical box centred at 32,32 by the
 * transform on its root <g>, with stroke-width = 1.5 / scale — so all 51
 * render at an identical 1.5-unit visual weight however far each drawing had to
 * be scaled to fit. That is what makes them read as one commissioned set rather
 * than 51 pieces of clip art, and it is not to be tidied away.
 *
 * The renderer supplies the <svg viewBox="0 0 64 64"> wrapper; each entry here
 * is its contents. Nothing names a colour — see the rule at the top of
 * src/app/plates.tsx.
 *
 * A missing key draws nothing and the tile still works, which is the correct
 * failure: a tone with no mark is a plainer tile, not a broken one.
 */
export const TONE_MARKS: Record<string, ReactNode> = {
  "absurd": (
    <>
    <g transform="translate(-0.81 -4.54) scale(1.2263)" fill="none" stroke="var(--ink)" strokeWidth="1.223" strokeLinecap="round" strokeLinejoin="round">
    <path d="M8 46 L26 46 C34 46 38 42 38 36 C38 30 33 27 29 29 C25 31 25 37 30 39 C36 41 43 38 45 31 C47 24 43 17 36 16" /><circle cx="36" cy="16" r="2.4" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "across_the_room": (
    <>
    <g transform="translate(1.08 -0.33) scale(0.9664)" fill="none" stroke="var(--ink)" strokeWidth="1.552" strokeLinecap="round" strokeLinejoin="round">
    <path d="M8.2 44 L17.8 44" stroke="var(--ink)" /><path d="M8.2 44 L8.2 35.2 M17.8 44 L17.8 35.2" stroke="var(--ink)" /><path d="M8.2 35.2 L17.8 35.2" stroke="var(--ink)" /><path d="M9 44 L9 50.4 M17 44 L17 50.4" stroke="var(--ink)" /><path d="M46.2 44 L55.8 44" stroke="var(--ink)" /><path d="M46.2 44 L46.2 35.2 M55.8 44 L55.8 35.2" stroke="var(--ink)" /><path d="M46.2 35.2 L55.8 35.2" stroke="var(--ink)" /><path d="M47 44 L47 50.4 M55 44 L55 50.4" stroke="var(--ink)" /><path d="M17 24 C26 14 38 14 47 24" stroke="var(--oxblood)" strokeDasharray="3 4" /><circle cx="47" cy="24" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "all_at_once": (
    <>
    <g transform="translate(-4.8 -5.95) scale(1.15)" fill="none" stroke="var(--ink)" strokeWidth="1.304" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 22 C20 16 28 20 30 28" /><path d="M52 24 C44 18 36 22 34 30" /><path d="M14 44 C22 50 30 46 32 38" /><path d="M50 42 C42 48 36 44 34 36" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "arrives_late": (
    <>
    <g transform="translate(-6.24 -4.8) scale(1.15)" fill="none" stroke="var(--ink)" strokeWidth="1.304" strokeLinecap="round" strokeLinejoin="round">
    <path d="M18 12 L18 52 L34 48 L34 16 Z" /><path d="M40 12 L40 52" /><circle cx="30" cy="32" r="2" fill="var(--oxblood)" stroke="none" /><path d="M44 24 C50 28 50 36 44 40" stroke="var(--oxblood)" strokeDasharray="3 3" />
    </g>
    </>
  ),
  "asks_properly": (
    <>
    <g transform="translate(-14.36 -14) scale(1.4375)" fill="none" stroke="var(--ink)" strokeWidth="1.043" strokeLinecap="round" strokeLinejoin="round">
    <path d="M18 28 L42 28 L40 42 C40 46 36 48 30 48 C24 48 20 46 20 42 Z" /><path d="M42 32 C48 32 48 40 42 40" /><circle cx="32" cy="18" r="2" fill="var(--oxblood)" stroke="none" /><path d="M26 18 L26 18.1 M38 18 L38 18.1" stroke="var(--ink)" />
    </g>
    </>
  ),
  "between_us": (
    <>
    <g transform="translate(-12.6 -17.48) scale(1.3939)" fill="none" stroke="var(--ink)" strokeWidth="1.076" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="32" cy="32" r="13" /><circle cx="32" cy="32" r="8" /><circle cx="32" cy="32" r="3" fill="var(--oxblood)" stroke="none" /><path d="M32 45 L32 52" />
    </g>
    </>
  ),
  "comfortable_silence": (
    <>
    <g transform="translate(-2.39 -12.39) scale(1.0748)" fill="none" stroke="var(--ink)" strokeWidth="1.396" strokeLinecap="round" strokeLinejoin="round">
    <path d="M10.6 44 L21.4 44" stroke="var(--ink)" /><path d="M10.6 44 L10.6 34.1 M21.4 44 L21.4 34.1" stroke="var(--ink)" /><path d="M10.6 34.1 L21.4 34.1" stroke="var(--ink)" /><path d="M11.5 44 L11.5 51.2 M20.5 44 L20.5 51.2" stroke="var(--ink)" /><path d="M42.6 44 L53.4 44" stroke="var(--ink)" /><path d="M42.6 44 L42.6 34.1 M53.4 44 L53.4 34.1" stroke="var(--ink)" /><path d="M42.6 34.1 L53.4 34.1" stroke="var(--ink)" /><path d="M43.5 44 L43.5 51.2 M52.5 44 L52.5 51.2" stroke="var(--ink)" /><circle cx="32" cy="34" r="2.6" fill="var(--oxblood)" stroke="none" /><path d="M32 42 L32 46" stroke="var(--oxblood)" strokeDasharray="2 3" />
    </g>
    </>
  ),
  "compliments_plainly": (
    <>
    <g transform="translate(-4.8 -6.24) scale(1.15)" fill="none" stroke="var(--ink)" strokeWidth="1.304" strokeLinecap="round" strokeLinejoin="round">
    <path d="M22 14 L42 14 L52 42 L12 42 Z" strokeDasharray="3 3" /><path d="M22 14 L42 14" /><circle cx="32" cy="48" r="4.5" fill="var(--oxblood)" stroke="none" /><path d="M24 42 L40 42" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "corrects_gently": (
    <>
    <g transform="translate(-1.46 -5.64) scale(1.0455)" fill="none" stroke="var(--ink)" strokeWidth="1.435" strokeLinecap="round" strokeLinejoin="round">
    <path d="M10 26 L54 26" /><path d="M10 38 L54 38" /><path d="M26 34 L32 28 L38 34" stroke="var(--oxblood)" /><circle cx="32" cy="44" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "deadpan": (
    <>
    <g transform="translate(-8.89 -1.61) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M32.0 15.1 L32.0 9.0" stroke="var(--oxblood)" /><path d="M35.5 16.5 L39.8 12.2" stroke="var(--oxblood)" /><path d="M37.0 20.0 L43.0 20.0" stroke="var(--oxblood)" /><path d="M35.5 23.5 L39.8 27.8" stroke="var(--oxblood)" /><path d="M32.0 24.9 L32.0 31.0" stroke="var(--oxblood)" /><path d="M28.5 23.5 L24.2 27.8" stroke="var(--oxblood)" /><path d="M27.1 20.0 L21.0 20.0" stroke="var(--oxblood)" /><path d="M28.5 16.5 L24.2 12.2" stroke="var(--oxblood)" /><path d="M14 42 L50 42" /><circle cx="32" cy="42" r="1.6" fill="var(--ink)" stroke="none" />
    </g>
    </>
  ),
  "does_the_voice": (
    <>
    <g transform="translate(-20.11 -19.75) scale(1.4375)" fill="none" stroke="var(--ink)" strokeWidth="1.043" strokeLinecap="round" strokeLinejoin="round">
    <path d="M22 20 C22 34 26 42 32 42 C38 42 42 34 42 20 Z" /><path d="M32 42 L32 52" /><circle cx="27" cy="26" r="1.8" fill="var(--ink)" stroke="none" /><circle cx="37" cy="26" r="1.8" fill="var(--ink)" stroke="none" /><path d="M46 22 C52 26 52 34 46 38" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "dressed_up": (
    <>
    <g transform="translate(-14 -14) scale(1.4375)" fill="none" stroke="var(--ink)" strokeWidth="1.043" strokeLinecap="round" strokeLinejoin="round">
    <path d="M32 32 L16 24 L16 40 Z" /><path d="M32 32 L48 24 L48 40 Z" /><circle cx="32" cy="32" r="3.2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "dry_aside": (
    <>
    <g transform="translate(-0.25 -13.55) scale(1.1275)" fill="none" stroke="var(--ink)" strokeWidth="1.33" strokeLinecap="round" strokeLinejoin="round">
    <path d="M18 26 L30 26 C30 35.75 27.3 39 24 39 C20.7 39 18 35.75 18 26 Z" stroke="var(--ink)" /><path d="M24 39 L24 45" stroke="var(--ink)" /><path d="M19 45 L29 45" stroke="var(--ink)" /><path d="M39 30 L49 30 C49 37.5 46.75 40 44 40 C41.25 40 39 37.5 39 30 Z" stroke="var(--ink)" /><path d="M44 40 L44 46" stroke="var(--ink)" /><path d="M39 46 L49 46" stroke="var(--ink)" /><path d="M18 40 C10 42 8 47 10 52" stroke="var(--oxblood)" /><circle cx="10" cy="53" r="1.8" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "exact_word": (
    <>
    <g transform="translate(-11.29 -9.94) scale(1.3529)" fill="none" stroke="var(--ink)" strokeWidth="1.109" strokeLinecap="round" strokeLinejoin="round">
    <path d="M22 14 L42 14 L38 40 L32 48 L26 40 Z" /><path d="M22 22 L42 22" /><path d="M32 26 L32 40" /><circle cx="32" cy="44" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "explains_nothing": (
    <>
    <g transform="translate(-16.88 -14) scale(1.4375)" fill="none" stroke="var(--ink)" strokeWidth="1.043" strokeLinecap="round" strokeLinejoin="round">
    <path d="M18 16 L44 16 L44 48 L18 48 Z" /><path d="M24 16 L24 48" /><path d="M44 28 L50 28 L50 36 L44 36" stroke="var(--oxblood)" /><circle cx="47" cy="32" r="1.8" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "first_names": (
    <>
    <g transform="translate(-29.33 -25.5) scale(1.9167)" fill="none" stroke="var(--ink)" strokeWidth="0.783" strokeLinecap="round" strokeLinejoin="round">
    <path d="M20 21.5 L44 21.5 L44 38.5 L20 38.5 Z" stroke="var(--ink)" /><path d="M22 34 L36 34" stroke="var(--oxblood)" /><path d="M44 22 L38 22 L38 28 Z" />
    </g>
    </>
  ),
  "good_natured": (
    <>
    <g transform="translate(-8.89 2.61) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M14 18 L28 18 C28 27 24 31 21 31 C18 31 14 27 14 18 Z" /><path d="M21 31 L21 40 M16 40 L26 40" /><path d="M36 18 L50 18 C50 27 46 31 43 31 C40 31 36 27 36 18 Z" /><path d="M43 31 L43 40 M38 40 L48 40" /><path d="M28 20 L36 20" /><path d="M32 12 L32 6 M24 13 L21 8 M40 13 L43 8" stroke="var(--gold)" />
    </g>
    </>
  ),
  "impeccably_polite": (
    <>
    <g transform="translate(-6.74 -7.95) scale(1.2105)" fill="none" stroke="var(--ink)" strokeWidth="1.239" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="32" cy="26" r="12" stroke="var(--ink)" /><path d="M32 26 L32 18" /><path d="M32 26 L40 26" stroke="var(--oxblood)" /><path d="M32 48 L20 42 L20 52 Z" /><path d="M32 48 L44 42 L44 52 Z" /><circle cx="32" cy="48" r="2.4" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "in_jokes": (
    <>
    <g transform="translate(-19.65 -22.47) scale(1.614)" fill="none" stroke="var(--ink)" strokeWidth="0.929" strokeLinecap="round" strokeLinejoin="round">
    <path d="M20 30 L44 30 L44 48 L20 48 Z" /><path d="M25 30 L25 24 C25 18 39 18 39 24 L39 30" /><circle cx="32" cy="37" r="2.6" fill="var(--oxblood)" stroke="none" /><path d="M32 39 L32 43" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "interrupts": (
    <>
    <g transform="translate(1.33 0.38) scale(0.9583)" fill="none" stroke="var(--ink)" strokeWidth="1.565" strokeLinecap="round" strokeLinejoin="round">
    <path d="M8 26 L30 26 L34 34 L38 26 L56 26" /><path d="M8 40 L26 40 M38 40 L56 40" /><circle cx="34" cy="34" r="2.2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "laughs_first": (
    <>
    <g transform="translate(1.33 -4.42) scale(0.9583)" fill="none" stroke="var(--ink)" strokeWidth="1.565" strokeLinecap="round" strokeLinejoin="round">
    <path d="M8 38 L24 38" /><path d="M33.0 34.0 L33.0 29.0" stroke="var(--oxblood)" /><path d="M35.9 35.1 L39.4 31.6" stroke="var(--oxblood)" /><path d="M37.0 38.0 L42.0 38.0" stroke="var(--oxblood)" /><path d="M35.9 40.9 L39.4 44.4" stroke="var(--oxblood)" /><path d="M33.0 42.0 L33.0 47.0" stroke="var(--oxblood)" /><path d="M30.1 40.9 L26.6 44.4" stroke="var(--oxblood)" /><path d="M28.9 38.0 L24.0 38.0" stroke="var(--oxblood)" /><path d="M30.1 35.1 L26.6 31.6" stroke="var(--oxblood)" /><path d="M42 38 L56 38" strokeDasharray="2 4" />
    </g>
    </>
  ),
  "leans_in": (
    <>
    <g transform="translate(-8.89 -11.45) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M14 26 L26 26 C26 35 23.3 38 20 38 C16.7 38 14 35 14 26 Z" stroke="var(--ink)" /><path d="M20 38 L20 44" stroke="var(--ink)" /><path d="M15 44 L25 44" stroke="var(--ink)" /><path d="M38 26 L50 26 C50 35 47.3 38 44 38 C40.7 38 38 35 38 26 Z" stroke="var(--ink)" /><path d="M44 38 L44 44" stroke="var(--ink)" /><path d="M39 44 L49 44" stroke="var(--ink)" /><path d="M28 24 C31 27 33 27 36 24" stroke="var(--oxblood)" /><circle cx="32" cy="30" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "lingers": (
    <>
    <g transform="translate(1.33 -4.42) scale(0.9583)" fill="none" stroke="var(--ink)" strokeWidth="1.565" strokeLinecap="round" strokeLinejoin="round">
    <path d="M8 44 L56 44" /><path d="M15 30 L25 30 C25 37.5 22.75 40 20 40 C17.25 40 15 37.5 15 30 Z" stroke="var(--ink)" /><path d="M20 40 L20 46" stroke="var(--ink)" /><path d="M15 46 L25 46" stroke="var(--ink)" /><path d="M39 30 L49 30 C49 37.5 46.75 40 44 40 C41.25 40 39 37.5 39 30 Z" stroke="var(--ink)" /><path d="M44 40 L44 46" stroke="var(--ink)" /><path d="M39 46 L49 46" stroke="var(--ink)" /><path d="M28.5 44 L28.5 37 L35.5 37 L35.5 44 Z" stroke="var(--ink)" /><path d="M26 44 L38 44" stroke="var(--ink)" /><path d="M32 37 C30.35 35.35 30.9 33.15 32 32.05 C33.1 33.15 33.65 35.35 32 37 Z" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "long_way_round": (
    <>
    <g transform="translate(0.71 -4.05) scale(1.036)" fill="none" stroke="var(--ink)" strokeWidth="1.448" strokeLinecap="round" strokeLinejoin="round">
    <path d="M10 46 C14 34 22 40 24 30 C26 20 36 24 38 32 C40 40 48 38 50 26" /><circle cx="10" cy="46" r="2" fill="var(--ink)" stroke="none" /><circle cx="50" cy="24" r="2.4" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "low_voices": (
    <>
    <g transform="translate(-2.5 2.68) scale(1.15)" fill="none" stroke="var(--ink)" strokeWidth="1.304" strokeLinecap="round" strokeLinejoin="round">
    <path d="M16 40 C16 26 20 18 30 16 C40 18 44 26 44 40 Z" /><path d="M13 40 L47 40" /><path d="M30 16 L30 11" /><path d="M10 30 L50 30" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "makes_an_entrance": (
    <>
    <g transform="translate(-8.89 -8.89) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M20 50 L20 28 C20 20 26 14 32 14 C38 14 44 20 44 28 L44 50" /><path d="M32.0 23.5 L32.0 18.0" stroke="var(--gold)" /><path d="M35.2 24.8 L39.1 20.9" stroke="var(--gold)" /><path d="M36.5 28.0 L42.0 28.0" stroke="var(--gold)" /><path d="M35.2 31.2 L39.1 35.1" stroke="var(--gold)" /><path d="M32.0 32.5 L32.0 38.0" stroke="var(--gold)" /><path d="M28.8 31.2 L24.9 35.1" stroke="var(--gold)" /><path d="M27.5 28.0 L22.0 28.0" stroke="var(--gold)" /><path d="M28.8 24.8 L24.9 20.9" stroke="var(--gold)" /><circle cx="32" cy="28" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "means_the_other_thing": (
    <>
    <g transform="translate(-8.89 -10.17) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M14 26 L44 26 M38 20 L44 26 L38 32" /><path d="M50 40 L20 40 M26 34 L20 40 L26 46" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "never_performs": (
    <>
    <g transform="translate(-4.8 -4.8) scale(1.15)" fill="none" stroke="var(--ink)" strokeWidth="1.304" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 14 L52 14" /><path d="M18 14 C18 30 16 42 14 50 M26 14 C26 32 25 44 24 50 M38 14 C38 32 39 44 40 50 M46 14 C46 30 48 42 50 50" /><path d="M32 14 L32 50" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "nicknames": (
    <>
    <g transform="translate(-11.29 -9.94) scale(1.3529)" fill="none" stroke="var(--ink)" strokeWidth="1.109" strokeLinecap="round" strokeLinejoin="round">
    <path d="M22 20 L42 20 L46 30 L42 48 L22 48 L18 30 Z" /><path d="M32 14 L32 20" /><circle cx="32" cy="26" r="2.6" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "no_dead_air": (
    <>
    <g transform="translate(7.47 7.47) scale(0.7667)" fill="none" stroke="var(--ink)" strokeWidth="1.956" strokeLinecap="round" strokeLinejoin="round">
    <path d="M4 32 C10 20 16 20 22 32 C28 44 34 44 40 32 C46 20 54 20 60 32" /><circle cx="4" cy="32" r="2" fill="var(--oxblood)" stroke="none" /><circle cx="60" cy="32" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "no_speeches": (
    <>
    <g transform="translate(-8.89 -8.89) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M25 22 L39 22 C39 31.75 35.85 35 32 35 C28.15 35 25 31.75 25 22 Z" stroke="var(--ink)" /><path d="M32 35 L32 41" stroke="var(--ink)" /><path d="M27 41 L37 41" stroke="var(--ink)" /><path d="M32 41 L32 48" /><path d="M14 50 L50 14" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "nothing_by_halves": (
    <>
    <g transform="translate(-20.57 -27.14) scale(1.6429)" fill="none" stroke="var(--ink)" strokeWidth="0.913" strokeLinecap="round" strokeLinejoin="round">
    <path d="M23 22 L41 22 C41 34 36.95 38 32 38 C27.05 38 23 34 23 22 Z" stroke="var(--ink)" /><path d="M32 38 L32 44" stroke="var(--ink)" /><path d="M27 44 L37 44" stroke="var(--ink)" /><path d="M32 44 L32 50" /><path d="M26 50 L38 50" /><path d="M23.5 24 L40.5 24" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "nothing_sacred": (
    <>
    <g transform="translate(1.33 -1.54) scale(0.9583)" fill="none" stroke="var(--ink)" strokeWidth="1.565" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 24 L12 46 M22 24 L22 46 M42 24 L42 46 M52 24 L52 46" /><path d="M8 30 L56 30 M8 40 L56 40" /><path d="M32 22 L32 48" stroke="var(--oxblood)" strokeDasharray="3 4" />
    </g>
    </>
  ),
  "one_conversation": (
    <>
    <g transform="translate(-14 -13.72) scale(1.4375)" fill="none" stroke="var(--ink)" strokeWidth="1.043" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="32" cy="32" r="14" /><circle cx="46" cy="32" r="2" fill="var(--ink)" stroke="none" /><circle cx="39" cy="44.12435565298214" r="2" fill="var(--ink)" stroke="none" /><circle cx="25.000000000000004" cy="44.124355652982146" r="2" fill="var(--ink)" stroke="none" /><circle cx="18" cy="32" r="2" fill="var(--ink)" stroke="none" /><circle cx="24.999999999999993" cy="19.87564434701786" r="2" fill="var(--ink)" stroke="none" /><circle cx="39" cy="19.87564434701786" r="2.4" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "one_tells_it": (
    <>
    <g transform="translate(-3.4 -1.95) scale(1.106)" fill="none" stroke="var(--ink)" strokeWidth="1.356" strokeLinecap="round" strokeLinejoin="round">
    <path d="M26 40 L38 40" stroke="var(--ink)" /><path d="M26 40 L26 29 M38 40 L38 29" stroke="var(--ink)" /><path d="M26 29 L38 29" stroke="var(--ink)" /><path d="M27 40 L27 48 M37 40 L37 48" stroke="var(--ink)" /><circle cx="13.20614758428183" cy="27.159597133486628" r="2" fill="var(--ink)" stroke="none" /><circle cx="21.999999999999993" cy="16.679491924311233" r="2" fill="var(--ink)" stroke="none" /><circle cx="42" cy="16.67949192431123" r="2" fill="var(--ink)" stroke="none" /><circle cx="50.79385241571817" cy="27.159597133486628" r="2" fill="var(--ink)" stroke="none" /><circle cx="32" cy="16" r="2.6" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "rises_to_greet": (
    <>
    <g transform="translate(-18.06 -18.06) scale(1.3529)" fill="none" stroke="var(--ink)" strokeWidth="1.109" strokeLinecap="round" strokeLinejoin="round">
    <path d="M20 42 L32 42" stroke="var(--ink)" /><path d="M20 42 L20 31 M32 42 L32 31" stroke="var(--ink)" /><path d="M20 31 L32 31" stroke="var(--ink)" /><path d="M21 42 L21 50 M31 42 L31 50" stroke="var(--ink)" /><path d="M40 44 C48 42 52 36 52 28" stroke="var(--oxblood)" strokeDasharray="3 3" /><circle cx="52" cy="26" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "roughly_eight": (
    <>
    <g transform="translate(-18.53 -14.36) scale(1.4488)" fill="none" stroke="var(--ink)" strokeWidth="1.035" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="32" cy="32" r="13" stroke="var(--ink)" /><path d="M32 32 L32 22" /><path d="M32 32 L41 37" stroke="var(--oxblood)" /><path d="M44 30 C50 30 52 34 50 38" stroke="var(--oxblood)" strokeDasharray="2 3" />
    </g>
    </>
  ),
  "says_it_out_loud": (
    <>
    <g transform="translate(0 5) scale(1)" fill="none" stroke="var(--ink)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
    <path d="M32 50 C20 42 14 34 14 28 C14 22 19 19 24 21 C27 22 30 25 32 29 C34 25 37 22 40 21 C45 19 50 22 50 28 C50 34 44 42 32 50 Z" /><path d="M32.0 8.4 L32.0 4.0" stroke="var(--gold)" /><path d="M35.1 10.2 L38.9 8.0" stroke="var(--gold)" /><path d="M35.1 13.8 L38.9 16.0" stroke="var(--gold)" /><path d="M32.0 15.6 L32.0 20.0" stroke="var(--gold)" /><path d="M28.9 13.8 L25.1 16.0" stroke="var(--gold)" /><path d="M28.9 10.2 L25.1 8.0" stroke="var(--gold)" />
    </g>
    </>
  ),
  "seating_plan": (
    <>
    <g transform="translate(-1.46 -11.39) scale(1.0455)" fill="none" stroke="var(--ink)" strokeWidth="1.435" strokeLinecap="round" strokeLinejoin="round">
    <path d="M10 44 L54 44" /><path d="M14 44 L20 35 L26 44 Z" stroke="var(--ink)" /><path d="M26 44 L32 35 L38 44 Z" stroke="var(--ink)" /><path d="M38 44 L44 35 L50 44 Z" stroke="var(--oxblood)" /><path d="M10 48 L54 48" />
    </g>
    </>
  ),
  "self_deprecating": (
    <>
    <g transform="translate(-11.37 -18.35) scale(1.3826)" fill="none" stroke="var(--ink)" strokeWidth="1.085" strokeLinecap="round" strokeLinejoin="round">
    <path d="M24 46 C12 46 12 30 22 26 C32 22 44 26 44 34" /><path d="M44 34 L40 30 M44 34 L48 30" /><path d="M44 34 C44 44 34 48 26 46" stroke="var(--oxblood)" strokeDasharray="3 3" /><circle cx="24" cy="46" r="2.4" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "sentimental": (
    <>
    <g transform="translate(-1.46 -3.55) scale(1.0455)" fill="none" stroke="var(--ink)" strokeWidth="1.435" strokeLinecap="round" strokeLinejoin="round">
    <path d="M32 12 L52 32 L32 52 L12 32 Z" /><path d="M22 32 C26 28 38 28 42 32 M26 38 C29 35 35 35 38 38" /><path d="M32 56 C29 53 30 49 32 47 C34 49 35 53 32 56 Z" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "spells_it_out": (
    <>
    <g transform="translate(-24.61 -23.73) scale(1.7692)" fill="none" stroke="var(--ink)" strokeWidth="0.848" strokeLinecap="round" strokeLinejoin="round">
    <path d="M19 19 L45 19 L45 41 L19 41 Z" stroke="var(--ink)" /><path d="M22 24 L42 24 M22 30 L42 30 M22 36 L36 36" /><path d="M22 44 L42 44" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "straight_to_gossip": (
    <>
    <g transform="translate(-8.89 -7.61) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M14 16 L14 22 C14 28 20 28 20 22" /><path d="M26 20 L20 20" /><path d="M22 26 L18 46 L30 46 L28 26 Z" /><path d="M38 28 L50 28 C50 37 47.3 40 44 40 C40.7 40 38 37 38 28 Z" stroke="var(--ink)" /><path d="M44 40 L44 46" stroke="var(--ink)" /><path d="M39 46 L49 46" stroke="var(--ink)" /><circle cx="44" cy="24" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "swears_fondly": (
    <>
    <g transform="translate(-5.4 -5.53) scale(1.2105)" fill="none" stroke="var(--ink)" strokeWidth="1.239" strokeLinecap="round" strokeLinejoin="round">
    <path d="M32 24 C26 24 22 20 24 15 C26 11 33 11 36 15 C39 19 37 24 32 24 Z" /><path d="M32 24 C29 22 28 18 30 15 M32 24 C35 22 36 18 34 15" /><path d="M32 24 L32 50" /><path d="M32 34 C26 34 22 31 21 27 C26 26 30 29 32 33" /><path d="M32 40 L38 36" stroke="var(--oxblood)" /><circle cx="39" cy="35" r="1.8" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "talks_fast": (
    <>
    <g transform="translate(2.73 -0.41) scale(1.0455)" fill="none" stroke="var(--ink)" strokeWidth="1.435" strokeLinecap="round" strokeLinejoin="round">
    <path d="M20 40 L26 24 L32 40 L38 22 L44 40 L50 26" /><path d="M6 28 L16 28" stroke="var(--oxblood)" /><path d="M9 34 L17 34" stroke="var(--oxblood)" />
    </g>
    </>
  ),
  "teasing": (
    <>
    <g transform="translate(3 2.5) scale(1)" fill="none" stroke="var(--ink)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
    <path d="M30 20 C30 13 24 9 18 9 C11 9 6 14 6 21 C6 29 13 34 18 34 C24 34 30 28 30 20 Z" /><path d="M18 34 L16 38 L20 38 L18 34" /><path d="M18 38 C18 44 14 46 16 50" /><path d="M52 12 L36 24" stroke="var(--oxblood)" /><circle cx="35" cy="25" r="2" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "toasts": (
    <>
    <g transform="translate(0 3) scale(1)" fill="none" stroke="var(--ink)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
    <path d="M24 26 L40 26 C40 36.5 36.4 40 32 40 C27.6 40 24 36.5 24 26 Z" stroke="var(--ink)" /><path d="M32 40 L32 46" stroke="var(--ink)" /><path d="M27 46 L37 46" stroke="var(--ink)" /><path d="M32 46 L32 52" /><path d="M32.0 10.4 L32.0 6.0" stroke="var(--gold)" /><path d="M35.1 12.2 L38.9 10.0" stroke="var(--gold)" /><path d="M35.1 15.8 L38.9 18.0" stroke="var(--gold)" /><path d="M32.0 17.6 L32.0 22.0" stroke="var(--gold)" /><path d="M28.9 15.8 L25.1 18.0" stroke="var(--gold)" /><path d="M28.9 12.2 L25.1 10.0" stroke="var(--gold)" />
    </g>
    </>
  ),
  "understated": (
    <>
    <g transform="translate(-1.46 -1.46) scale(1.0455)" fill="none" stroke="var(--ink)" strokeWidth="1.435" strokeLinecap="round" strokeLinejoin="round">
    <path d="M10 18 L10 46 M54 18 L54 46" strokeDasharray="2 4" /><path d="M28 32 L36 32" /><circle cx="42" cy="32" r="1.8" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "unhurried": (
    <>
    <g transform="translate(-2.5 -2.5) scale(1.15)" fill="none" stroke="var(--ink)" strokeWidth="1.304" strokeLinecap="round" strokeLinejoin="round">
    <path d="M14 10 L46 10 M14 50 L46 50" /><path d="M17 10 C17 22 30 26 30 30 C30 34 17 38 17 50 L43 50 C43 38 30 34 30 30 C30 26 43 22 43 10 Z" /><circle cx="30" cy="31" r="1.6" fill="var(--oxblood)" stroke="none" /><circle cx="30" cy="42" r="2.4" fill="var(--oxblood)" stroke="none" />
    </g>
    </>
  ),
  "warm_not_loud": (
    <>
    <g transform="translate(-17.48 -16.13) scale(1.5462)" fill="none" stroke="var(--ink)" strokeWidth="0.97" strokeLinecap="round" strokeLinejoin="round">
    <path d="M22.5 46 L22.5 31 L29.5 31 L29.5 46 Z" stroke="var(--ink)" /><path d="M20 46 L32 46" stroke="var(--ink)" /><path d="M34.5 46 L34.5 31 L41.5 31 L41.5 46 Z" stroke="var(--ink)" /><path d="M32 46 L44 46" stroke="var(--ink)" /><path d="M26 31 C23.45 28.45 24.3 25.05 26 23.35 C27.7 25.05 28.55 28.45 26 31 Z" stroke="var(--gold)" /><path d="M38 31 C35.45 28.45 36.3 25.05 38 23.35 C39.7 25.05 40.55 28.45 38 31 Z" stroke="var(--gold)" /><path d="M20 20 C26 15 38 15 44 20" stroke="var(--gold)" />
    </g>
    </>
  ),
  "will_look_it_up": (
    <>
    <g transform="translate(-8.89 -8.89) scale(1.2778)" fill="none" stroke="var(--ink)" strokeWidth="1.174" strokeLinecap="round" strokeLinejoin="round">
    <path d="M20 14 L44 14 L44 50 L20 50 Z" /><path d="M28 46 L36 46" /><circle cx="32" cy="28" r="7" stroke="var(--oxblood)" /><path d="M37 33 L43 39" stroke="var(--oxblood)" />
    </g>
    </>
  ),
};
